# .github/workflows/go.yml

name: Go Tests

on: # Defines the triggers for the workflow
  push: # Runs on pushes to any branch
    branches:
      - main # Or your default branch (e.g., master)
      - 'feature/**' # Example: also run on branches like feature/new-thing
  pull_request: # Runs on pull requests targeting the main branch
    branches:
      - main # Or your default branch

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.22.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install dependencies)
        run: go mod download

      - name: Run tests
        run: go test -v ./pkg/... -coverprofile=coverage.txt

      - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}